name: Node CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn install
    - name: Install hummus
      run: npm install -g --unsafe-perm hummus
    - name: Temporarily fix electron-builder
      run: |
        sed -i '' 's/\^\[\\w/\^\[.\\w/g' node_modules/builder-util/out/util.js
      shell: bash
    - name: Build
      run: yarn distAll
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
