name: Node CD

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn install
    - name: Temporarily fix electron-builder
      run: |
        sed -i '' 's/\^\[\\w/\^\[.\\w/g' node_modules/builder-util/out/util.js
      shell: bash
    - name: Build
      run: yarn dist
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Git Tag
        run: git tag $(date +'%Y%m%d%H%M%S')
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/*.zip
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
